name: CI build

# on push any branch
on:
  push:


jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Checkout tinkar-core repo
        uses: actions/checkout@v4
        with:
          repository: 'ikmdev/tinkar-core'
          path: tinkar-core

      - name: Build tinkar-core
        working-directory: tinkar-core
        run: mvn clean install

      - name: Build Komet
        run: |
          mvn clean install